name: Python package

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 skfair
        flake8 tests
        flake8 setup.py
    - name: Test with pytest
      run: |
        pip install pytest
        pytest
    - name: Doctest
      run: python -m doctest -v skfair/*.py
    - name: Notebook Test
      run: pytest --nbval-lax doc/*.ipynb
